apps/images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create_image_set/', views.ImageSetCreateView.as_view(),
         name='imageset_create_url'),

    path('<int:pk>/update_image_set/', views.ImageSetUpdateView.as_view(),
         name='imageset_update_url'),

    path('image_set_list/', views.ImageSetListView.as_view(),
         name='imageset_list_url'),

    path('<int:pk>/imageset/', views.ImageSetDetailView.as_view(),
         name='imageset_detail_url'),

    path('<int:pk>/upload_images/', views.ImagesUploadView.as_view(),
         name='upload_images_url'),

    path('<int:pk>/images_list/', views.ImagesListView.as_view(),
         name='images_list_url'),

    path('<int:imgset_pk>/delete_image/<int:pk>/', views.ImagesDeleteUrl.as_view(),
         name='image_delete_url'),
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    ########### User Account #############
    path('register/',
         views.register,
         name='register'
         ),

    path('profile/',
         views.profile,
         name='profile'
         ),

    path('registration_under_approval/',
         views.RegistrationUnderApproval.as_view(
             template_name='users/registration_under_approval.html'),
         name='registration_under_approval_url'
         ),

    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),

    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'
         ),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'),
         name='password_reset'
         ),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'
         ),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'
         ),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeTemplateView.as_view(), name="home_url"),
    path('users/', include('users.urls', namespace='users')),

    path('detectobj/', include("detectobj.urls", namespace="detectobj")),
    path('modelmanager/', include("modelmanager.urls", namespace="modelmanager")),
    # path('croppedimages/', include("croppedimages.urls", namespace="croppedimages")),
    path('images/', include("images.urls", namespace="images")),
    # path('test/', include("test_app.urls", namespace="test_app")),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

templates/partials/_leftbar.html
{% load static %}
{% if imageset %}
<a type="button" class="btn btn-sm btn-outline-info mb-2" href="{% url 'images:upload_images_url' imageset.id %}">Upload More images</a>
{% endif %}
{% if image %}
<div class="card">
    <div class="card-body">
        <div class="row">
            {% for image in images %}
            {% with image.get_imageurl as imgurl %}
                <div class="col-md">
                    <a href="{% url 'images:detect_object_url' image.image_set.id image.id %}">
                        <img src="{{ imgurl }}" alt="" class="mb-2 mr-1" width="90px" height="90px" />
                    </a>
                </div>
            {% endwith %}
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}

templates/partials/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top fixed-top mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home_url' %}">Django-obj-detection</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" href="#">{{ request.user|capfirst }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'users:logout' %}">logout</a>
          </li>
        {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </div>
</nav>

templates/partials/_paginator.html
    {% if is_paginated %}
        {% if page_obj.has_previous %}
          <a class="btn btn-outline-info btn-sm mb-4" href="?page=1">First</a>
          <a class="btn btn-outline-info btn-sm mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info btn-sm mb-4" href="?page={{ num }}">{{ num }}</a>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <a class="btn btn-outline-info btn-sm mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
          <a class="btn btn-outline-info btn-sm mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}

templates/partials/_scripts.html
{% load static %}
<script src="{% static 'js/vendor/jquerry.js' %}"></script>
<script src="{% static 'js/vendor/popper.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/lightbox_bs5.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/site_js.js' %}"></script>