apps/detectobj/urls.py
from django.urls import path
from . import views

app_name = "detectobj"

urlpatterns = [
    path("<int:pk>/selected_image/",
         views.InferenceImageDetectionView.as_view(),
         name="detection_image_detail_url"
         ),
]

apps/images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create_image_set/', views.ImageSetCreateView.as_view(),
         name='imageset_create_url'),

    path('<int:pk>/update_image_set/', views.ImageSetUpdateView.as_view(),
         name='imageset_update_url'),

    path('image_set_list/', views.ImageSetListView.as_view(),
         name='imageset_list_url'),

    path('<int:pk>/imageset/', views.ImageSetDetailView.as_view(),
         name='imageset_detail_url'),

    path('<int:pk>/upload_images/', views.ImagesUploadView.as_view(),
         name='upload_images_url'),

    path('<int:pk>/images_list/', views.ImagesListView.as_view(),
         name='images_list_url'),

    path('<int:imgset_pk>/delete_image/<int:pk>/', views.ImagesDeleteUrl.as_view(),
         name='image_delete_url'),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeTemplateView.as_view(), name="home_url"),
    path('users/', include('users.urls', namespace='users')),

    path('detectobj/', include("detectobj.urls", namespace="detectobj")),
    path('modelmanager/', include("modelmanager.urls", namespace="modelmanager")),
    # path('croppedimages/', include("croppedimages.urls", namespace="croppedimages")),
    path('images/', include("images.urls", namespace="images")),
    # path('test/', include("test_app.urls", namespace="test_app")),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

apps/images/models.py
import os
from PIL import Image as I

from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from config.models import CreationModificationDateBase


class ImageSet(CreationModificationDateBase):
    name = models.CharField(max_length=100,
                            help_text="eg. Delhi-trip, Tajmahal, flowers"
                            )
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='imagesets',
                             on_delete=models.CASCADE
                             )
    dirpath = models.CharField(max_length=150, null=True, blank=True)
    public = models.BooleanField(default=False)

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['user', 'name'],
            name='unique_imageset_by_user')]

    def __str__(self):
        return f'{self.name.capitalize()}'

    def get_dirpath(self):
        return os.path.join(self.user.username, self.name)

    def get_absolute_url(self):
        return reverse("images:imageset_detail_url", kwargs={"pk": self.pk})


def imageset_upload_images_path(instance, filename):
    return f'{instance.image_set.dirpath}/images/{filename}'


class ImageFile(models.Model):
    name = models.CharField(_('Image Name'), max_length=150, null=True)
    image_set = models.ForeignKey('images.ImageSet',
                                  related_name="images",
                                  on_delete=models.CASCADE,
                                  help_text="Image Set of the uploading images"
                                  )
    image = models.ImageField(upload_to=imageset_upload_images_path)

    is_inferenced = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    @ property
    def get_imageurl(self):
        return self.image.url

    @ property
    def get_imagepath(self):
        return self.image.path

    @ property
    def get_filename(self):
        return os.path.split(self.image.url)[-1]

    @ property
    def get_imgshape(self):
        im = I.open(self.get_imagepath)
        return im.size

    def get_delete_url(self):
        return reverse("images:images_list_url", kwargs={"pk": self.image_set.id})

    def save(self, *args, **kwargs):
        # Convert image to 640px before saving.
        super().save(*args, **kwargs)

        img = I.open(self.get_imagepath)
        if img.height > 640 or img.width > 640:
            output_size = (640, 640)
            img.thumbnail(output_size)
            img.save(self.get_imagepath)

apps/images/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from django.views.generic import View
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import ImageSet, ImageFile


class ImageSetCreateView(LoginRequiredMixin, CreateView):
    model = ImageSet
    fields = ['name', 'description', 'public']

    def form_valid(self, form):
        if not ImageSet.objects.filter(name=form.instance.name).exists():
            form.instance.user = self.request.user
            form.instance.dirpath = form.instance.get_dirpath()
            return super().form_valid(form)
        else:
            form.add_error(
                'name',
                f"Imageset with name {form.cleaned_data['name']} already exists in dataset. \
                     Add more images to that imageset, if required."
            )
            return HttpResponseRedirect(reverse('images:imageset_create_url'))


class ImageSetUpdateView(LoginRequiredMixin, UpdateView):
    model = ImageSet
    fields = ['name', 'description', 'public']

    def form_valid(self, form):
        if not ImageSet.objects.filter(name=form.instance.name).exists():
            return super().form_valid(form)
        print("entered in else")
        form.add_error(
            'name',
            f"Imageset with name {form.cleaned_data['name']} already exists in dataset. \
                     Add more images to that imageset, if required."
        )
        context = {
            'form': form
        }
        return render(self.request, 'images/imageset_form.html', context)

    def get_success_url(self):
        return reverse('images:imageset_detail_url', kwargs={'pk': self.object.id})


class ImageSetListView(LoginRequiredMixin, ListView):
    model = ImageSet
    context_object_name = 'imagesets'
    paginate_by: int = 10

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        public_imagesets = ImageSet.objects.filter(
            public=True).order_by('-created')
        user_imagesets = ImageSet.objects.filter(
            user=self.request.user).order_by('-created')
        context["public_imagesets"] = public_imagesets
        context["user_imagesets"] = user_imagesets
        return context


class ImageSetDetailView(LoginRequiredMixin, DetailView):
    model = ImageSet
    context_object_name = 'imageset'


class ImagesUploadView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        imageset_id = self.kwargs.get("pk")
        imageset = get_object_or_404(ImageSet, id=imageset_id)
        context = {
            'imageset': imageset,
        }
        return render(request, 'images/imagefile_form.html', context)

    def post(self, request, *args, **kwargs):
        imageset_id = self.kwargs.get("pk")
        imageset = get_object_or_404(ImageSet, id=imageset_id)
        if self.request.method == 'POST':
            images = [
                self.request.FILES.get("file[%d]" % i)
                for i in range(len(self.request.FILES))
            ]
            for img in images:
                if not ImageFile.objects.filter(name=img.name, image_set=imageset).exists():
                    ImageFile.objects.create(
                        name=img.name, image=img, image_set=imageset)

                else:
                    print(f"Image {img.name} already exists in the imageset.")

            message = f"Uploading images to the Imageset: {imageset}. \
                Automatic redirect to the images list after completion."

            redirect_to = reverse_lazy(
                "images:images_list_url", args=[imageset.id])
            return JsonResponse({"result": "result",
                                "message": message,
                                 "redirect_to": redirect_to,
                                 "files_length": len(images),
                                 },
                                status=200,
                                content_type="application/json"
                                )


class ImagesListView(LoginRequiredMixin, ListView):
    model = ImageFile
    context_object_name = 'images'

    def get_queryset(self):
        imageset_id = self.kwargs.get('pk')
        return super().get_queryset().filter(image_set__id=imageset_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        imageset_id = self.kwargs.get('pk')
        imageset = get_object_or_404(ImageSet, id=imageset_id)
        context["imageset"] = imageset
        return context


class ImagesDeleteUrl(LoginRequiredMixin, DeleteView):
    model = ImageFile

    def get_success_url(self):
        qs = self.get_object()
        return qs.get_delete_url()

apps/images/templates/images/imagefile_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Confirm delete - Image in {{ object.image_set.name }}
{% endblock title %}

{% block leftbar %}
<div class="col-md-3">
    {% include 'images/partials/_leftbar.html' %}
</div>
{% endblock leftbar %}

{% block content %}
<div class="col-md-8 mt-2">
    <form action="" method="post">
    {% csrf_token %}
      <div class="alert alert-danger" role="alert">
      You are about to delete the Image "{{ object.get_filename|capfirst }}".
      </div>
    <input type="submit" value="Confirm Delete" class="btn btn-outline-danger">
  </form>
</div>
{% endblock content %}

apps/images/templates/images/imagefile_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block on_page_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/basic.min.css' %}" > 
  <link rel="stylesheet" type="text/css" href="{% static 'css/dropzone.min.css' %}" />
{% endblock on_page_css %}

{% block title %}
{{imageset.name|capfirst}} - Images upload
{% endblock title %}


{% block content %}
    <div class="col-md-11 mx-4">
        <h4 class="mb-4">Upload images to {{ imageset.name|capfirst }} image set.</h4>
        <form action="{% url 'images:upload_images_url' imageset.id %}" method="post" enctype="multipart/form-data" class="dropzone dz" id="DzImageImport" >
            {% csrf_token %}
            <div class="dz-default dz-message upload_client">
                Drag & Drop Image files here or <strong>click here</strong> to upload.
            </div>
        </form>
        <button id="imagesUploadBtn" type="submit" class="btn btn-sm btn-outline-info mt-2">Submit</button>
    </div>
{% endblock content %}

{% block on_page_js %}
<script src="{% static 'js/dropzone.min.js' %}"></script>

<script>
    {% include 'images/partials/_dzconfig.html' %}
</script>

{% endblock on_page_js %}

apps/images/templates/images/imagefile_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Multiple images list
{% endblock title %}

{% block content %}
<div class="col-md-9 mt-2">
    <div class="row">
        {% for image in images %}
            {% with image.get_imageurl as imgurl %}
            <div class="col-sm-3">
                <a href="{{ imgurl }}" data-toggle="lightbox" data-gallery="image-gallery">
                    <img src="{{ imgurl }}" alt="" class="img-fluid mx-1 my-1" width="250px" height="250px" />
                </a>
                <a href="{% url 'images:image_delete_url' image.image_set.id image.id %}" class="btn btn-sm btn-outline-success mx-1 my-1">
                    <img src="{% static 'img/cross.png' %}" alt="" />
                </a>
                <a href="{% url 'detectobj:detection_image_detail_url' image.id %}" class="btn btn-sm btn-outline-success mx-1 my-1">
                    Detect Objects
                </a>
            </div>
            {% endwith %}
        {%empty%}
            <div class="card">
                <div class="card-body">
                    Nil image to display!
                </div>
            </div>
        {% endfor %}
    </div>
    
</div>
{% endblock content %}

apps/images/templates/images/imageset_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ imageset.name }} - ImageSet
{% endblock title %}

{% block content %}
<div class="col-md-10 mx-4">
    <div class="card">
    <div class="card-header">
        {{ imageset.name|capfirst }} - Image set
    </div>
    <div class="card-body">
       <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>Uploaded by</b>: {{ imageset.user|capfirst }}</li>
            <li class="list-group-item"><b>Total images</b>: {{ imageset.images.count }}</li>
            <li class="list-group-item"><b>Description</b>: {{ imageset.description }}</li>
            <li class="list-group-item"><b>Created on</b>: {{ imageset.created }}</li>
            <li class="list-group-item"><b>Updated on</b>: {{ imageset.modified }}</li>
        </ul>
        {% if imageset.user == request.user %}
            <a href="{% url 'images:upload_images_url' imageset.id %}" class="btn btn-outline-info btn-sm">Upload images</a>
            <a href="{% url 'images:imageset_update_url' imageset.id %}" class="btn btn-outline-info btn-sm">Update ImageSet</a>
            {% if imageset.images.count > 0 %}
                <a href="{% url 'images:images_list_url' imageset.id %}" class="btn btn-outline-info btn-sm">View Images</a>
            {% endif %}
        {% elif imageset.public and imageset.images.count > 0 %}
            <a href="{% url 'images:images_list_url' imageset.id %}" class="btn btn-outline-info btn-sm">View Images</a>
        {% endif %}
    </div>
    </div>    
</div>
{% endblock content %}

{% block shared_data %}
    {{ orig_image.id|json_script:"imageId" }}
{% endblock shared_data %}

apps/images/templates/images/imageset_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block title %}
Create images set
{% endblock title %}

{% block leftbar %}
<div class="col-md-3">
    {% include 'images/partials/_leftbar.html' %}
</div>
{% endblock leftbar %}

{% block content %}
    <div class="col-md-7">
        <legend class="border-bottom">
        {% if 'update' in request.path %}
            Update
        {% else %}
            Create
        {% endif %}
             Image Set
        </legend>
        <form action="" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-sm btn-outline-info mt-2">
            {% if 'update' in request.path %}
                Update
            {% else %}
                Create
            {% endif %}
            </button>
        </form>
    </div>
{% endblock content %}

apps/images/templates/images/imageset_list.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block title %}
Imagesets
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="d-flex justify-content-center mb-2">
            <a class="btn btn-sm btn-outline-success mx-1" type="button" href="{% url 'images:imageset_create_url' %}">Create imageset</a>
        </div>
        <div class="d-flex align-items-start">
            <div style="width:20%" class="nav flex-column nav-pills me-5" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                <button class="nav-link active" id="v-pills-public-tab" data-bs-toggle="pill" data-bs-target="#v-pills-public" type="button" role="tab" aria-controls="v-pills-public" aria-selected="true">Public image sets</button>
                <button class="nav-link" id="v-pills-user-tab" data-bs-toggle="pill" data-bs-target="#v-pills-user" type="button" role="tab" aria-controls="v-pills-user" aria-selected="false">My image sets</button>
            </div>
            <div class="tab-content" id="v-pills-tabContent" style="width:80%">
                <div class="tab-pane fade show active" id="v-pills-public" role="tabpanel" aria-labelledby="v-pills-public-tab" tabindex="0">
                    {% for imgset in public_imagesets %}
                        <div class="card mb-3">
                            <div class="card-header">
                                <a href="{% url 'images:imageset_detail_url' imgset.id %}">{{ imgset }}</a>
                            </div>
                            <div class="card-body">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item"><b>Uploaded by</b>: {{ imgset.user|capfirst }}</li>
                                    <li class="list-group-item"><b>Total images</b>: {{ imgset.images.count }}</li>
                                </ul>
                            </div>
                        </div>
                    {% empty %}
                        <div class="card">
                            <div class="card-header">
                                No public imageset created Yet!
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="tab-pane fade" id="v-pills-user" role="tabpanel" aria-labelledby="v-pills-user-tab" tabindex="0">
                    {% for imgset in user_imagesets %}
                        <div class="card mb-3">
                            <div class="card-header">
                                <a href="{% url 'images:imageset_detail_url' imgset.id %}">{{ imgset }}</a>
                            </div>
                            <div class="card-body">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item"><b>Uploaded by</b>: {{ imgset.user|capfirst }}</li>
                                    <li class="list-group-item"><b>Total images</b>: {{ imgset.images.count }}</li>
                                </ul>
                            </div>
                        </div>
                    {% empty %}
                        <div class="card">
                            <div class="card-body">
                                Nil Imageset Created Yet!
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>




        
    </div>
{% endblock content %}