apps/images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create_image_set/', views.ImageSetCreateView.as_view(),
         name='imageset_create_url'),

    path('<int:pk>/update_image_set/', views.ImageSetUpdateView.as_view(),
         name='imageset_update_url'),

    path('image_set_list/', views.ImageSetListView.as_view(),
         name='imageset_list_url'),

    path('<int:pk>/imageset/', views.ImageSetDetailView.as_view(),
         name='imageset_detail_url'),

    path('<int:pk>/upload_images/', views.ImagesUploadView.as_view(),
         name='upload_images_url'),

    path('<int:pk>/images_list/', views.ImagesListView.as_view(),
         name='images_list_url'),

    path('<int:imgset_pk>/delete_image/<int:pk>/', views.ImagesDeleteUrl.as_view(),
         name='image_delete_url'),
]

apps/modelmanager/urls.py
from django.urls import path
from . import views
app_name = 'modelmanager'

urlpatterns = [
    path('upload_ml_model',
         views.MLModelCreateView.as_view(),
         name='mlmodel_upload_url'
         ),
    path('ml_model_update/',
         views.MLModelUpdateView.as_view(),
         name='mlmodel_update_url'
         ),
    path('user/ml_model_list/',
         views.UserMLModelListView.as_view(),
         name='user_mlmodel_list_url'
         ),
    path('public/ml_model_list',
         views.PublicMLModelListView.as_view(),
         name='public_mlmodel_list_url'
         ),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeTemplateView.as_view(), name="home_url"),
    path('users/', include('users.urls', namespace='users')),

    path('detectobj/', include("detectobj.urls", namespace="detectobj")),
    path('modelmanager/', include("modelmanager.urls", namespace="modelmanager")),
    # path('croppedimages/', include("croppedimages.urls", namespace="croppedimages")),
    path('images/', include("images.urls", namespace="images")),
    # path('test/', include("test_app.urls", namespace="test_app")),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% block page_meta %}
  {% endblock %}

  {% block vendor_css %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'css/vendor/bootstrap.min.css' %}" />
    <link href="{% static 'css/ekko-lightbox.css' %}" rel="stylesheet">
  {% endblock vendor_css %}

  {% block site_css %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'css/styles/style.css' %}" />
  {% endblock %}

  {# Page-specific styles #}
  {% block on_page_css %}{% endblock %}

  {% block extra_head %}
    {# Extra header stuff (scripts, styles, metadata, etc) #}
  {% endblock %}

  <title>My Website - {% block title %}{% endblock %}</title>
</head>
<body class="{% block body_class %}{% endblock %}">
  {% include 'partials/_nav.html' %}

  {{ form.image.errors }}
<div class="fluid-container mx-2">
    
  {% block header %}
    {% include 'partials/_header.html' %}
  {% endblock header %}


  {% if messages %}
      {% for message in messages %}
        <div class="message">
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" id="djangoMessage" role="alert">
            {{ message }}
            <button type="button" class="close" aria-label="Close" data-dismiss="alert">
              <span aria-hidden="true" id="messageDialogCloseBtn">&times;</span></button>       
          </div>
        </div>    
      {% endfor %}
    {% endif %}

  <div class="row">
    {% block leftbar %}
        {# Leftbar on the Page #}
    {% endblock %}
    {% block content %}
        {# Page content will go here #}
    {% endblock %}
  </div>
</div>  

{# Modal HTML #}
{% block modals %}
{% endblock %}

{# Vendor javascript #}
{% block vendor_js %}
{% endblock %}

{# Global javascript #}
{% block site_js %}
  {% include 'partials/_scripts.html' %}
{% endblock %}

{# Shared data for javascript #}
{% block shared_data %}
{% endblock %}

{# On Page javascript #}
{% block on_page_js %}
{% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Home Page
{% endblock title %}

{% block content %}
<div class="col-md-12 mt-2">
    <div class="card">
    <h4 class="card-header">Django Object Detection With YoloV5</h4>
    <div class="card-body">
        <h5 class="card-title">Features of the WebApp:</h5>

        <ul class="list-group list-group-flush">
            <li class="list-group-item">Create imagesets & upload multiple images: 
                <a href="{% url 'images:imageset_create_url' %}" class="btn btn-sm btn-outline-success" type="button">Create Imageset</a>
                {% if user_imagesets %}
                <a href="{% url 'images:imageset_list_url' %}" class="btn btn-sm btn-outline-success" type="button">My ImageSets List</a>
                {% endif %}
                {% if public_imagesets %}
                <a href="{% url 'images:imageset_list_url' %}" class="btn btn-sm btn-outline-success" type="button">Public ImageSets List</a>
                {% endif %}
            </li>
            <li class="list-group-item">Convert uploaded image size to 640 x 640. (For faster detection)</li>
            <li class="list-group-item">Upload a custom pre-trained model: 
                <a href="{% url 'modelmanager:mlmodel_upload_url' %}" class="btn btn-sm btn-outline-success" type="button">Upload Pre-trained Model</a>
                <a href="{% url 'modelmanager:public_mlmodel_list_url' %}" class="btn btn-sm btn-outline-success" type="button">ML Models List</a>
            </li>
            <li class="list-group-item">You can upload any pre-trained model or a yolov5 model.</li>
            <li class="list-group-item">Detect object on an image with default/pre-trained model.
            </li>
        </ul>
    </div>
    </div>
</div>  
{% endblock content %}